kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: external-secret-2-bw-cli
  labels:
    app.kubernetes.io/instance: bitwarden-external-secrets
    app.kubernetes.io/part-of: external-secrets
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: bitwarden-external-secrets
  ingress:
  - from:
      - podSelector:
          matchLabels:
            app.kubernetes.io/part-of: external-secrets
