apiVersion: v1
kind: ServiceAccount
metadata:
  name: bitwarden-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bitwarden-operator
rules:
- apiGroups: ["bitwarden.external-secrets.io"]
  resources: ["bitwardensecrets"]
  verbs: ["get", "list", "watch", "patch", "update"]
- apiGroups: ["bitwarden.external-secrets.io"]
  resources: ["bitwardensecrets/status"]
  verbs: ["patch", "update"]
- apiGroups: ["external-secrets.io"]
  resources: ["externalsecrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["namespaces", "secrets"]
  verbs: ["get", "list", "watch", "create"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch", "update"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bitwarden-operator
subjects:
- kind: ServiceAccount
  name: bitwarden-operator
roleRef:
  kind: ClusterRole
  name: bitwarden-operator
  apiGroup: rbac.authorization.k8s.io
