apiVersion: v1
kind: Service
metadata:
  name: bitwarden-cli
  labels:
    app.kubernetes.io/instance: bitwarden-external-secrets
    app.kubernetes.io/part-of: external-secrets
spec:
  type: ClusterIP
  ports:
  - port: 8087
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/instance: bitwarden-external-secrets
