image:
  repository: ghcr.io/eznix86/bitwarden-cli
  pullPolicy: IfNotPresent
  tag: latest

operator:
  image:
    repository: ghcr.io/eznix86/bitwarden-operator
    pullPolicy: IfNotPresent
    tag: latest

secrets:
  bw_clientid: ""
  bw_clientsecret: ""
  bw_password: ""
  bw_host: "https://bitwarden.com"

external-secrets:
  installCRDs: false
  crds:
    createClusterResourcesEnabled: false