apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: bitwardensecrets.bitwarden.external-secrets.io
spec:
  group: bitwarden.external-secrets.io
  names:
    kind: BitwardenSecret
    plural: bitwardensecrets
    singular: bitwardensecret
    shortNames:
      - bws
  scope: Cluster
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - namespace
                - secrets
              properties:
                namespace:
                  type: string
                  x-kubernetes-preserve-unknown-fields: true
                secrets:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                  additionalProperties:
                    type: object
                    required:
                      - itemRef
                    properties:
                      itemRef:
                        type: object
                        required:
                          - id
                          - type
                        properties:
                          id:
                            type: string
                            description: "Bitwarden item ID"
                          type:
                            type: string
                            enum: [login, note, field, sshKey]
                            description: "Type of Bitwarden item"
                          property:
                            type: string
                            description: "Property to retrieve from the item"
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
      additionalPrinterColumns:
        - name: Status
          type: string
          jsonPath: .status.externalSecretStatus
        - name: Ready
          type: boolean
          jsonPath: .status.ready
        - name: Namespace
          type: string
          jsonPath: .spec.namespace
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
