services:
  bitwarden-cli:
    image: eznix86/bitwarden-operator:latest
    container_name: bitwarden-cli
    command: /bin/sh -c "while true; do sleep 30; done;"
    # volumes:
    #   - ./entrypoint.sh:/entrypoint.sh
    ports:
      - "8087:8087"
    env_file:
      - .env
    