name: Release Charts

on:
  push:
    branches:
      - main
    # paths:
    #   - charts/**

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: add repos
        run: |
          helm repo add external-secrets https://charts.external-secrets.io

      - name: Run chart-releaser
        id: cr
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ github.token }}"
        with:
          charts_dir: ./charts
